version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Configuração de conexão da API com o SQL Server remoto
      ConnectionStrings__ZivoMDatabase: "Data Source=SQL5111.site4now.net;Initial Catalog=db_a9af87_zivom;User Id=db_a9af87_zivom_admin;Password="
      ASPNETCORE_ENVIRONMENT: "Production"
      # Configurações do Keycloak para a API
      Keycloak__Authority: "http://localhost:8080/realms/zivoapp"
      Keycloak__ClientId: "zivoclient"
    ports:
      - "7676:8080"  # Porta externa 7676 mapeando para a interna 8080
    depends_on:
      - keycloak
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      # Conexão para o PostgreSQL local (na máquina host), com a porta correta
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5433/zivom_keycloak
      KC_DB_USERNAME: postgres  # Substitua se o usuário for diferente
      KC_DB_PASSWORD: "@asafe2020"  # Substitua se a senha for diferente
      KC_PROXY: edge
    ports:
      - "8080:8080"
    restart: always
    command: ["start-dev"]  # Adicione este comando para iniciar o servidor em modo de desenvolvimento
