version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__ZivoMDatabase: "Server=postgres;Database=keycloak;User Id=keycloak;Password=mysecurepassword"
    ports:
      - "5000:5000" 
    depends_on:
      - keycloak
      - postgres
    restart: always 

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: mysecurepassword
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
